#NAME: Senyang Jiang
#EMAIL: senyangjiang@yahoo.com
#ID: 505111806

all: lab1a.c
	@gcc -Wall -Wextra lab1a.c -o lab1a
clean:
	@rm -f lab1a lab1a-505111806.tar.gz
dist:
	@tar -czf lab1a-505111806.tar.gz Makefile lab1a.c README
