#NAME: Senyang Jiang, Max Zhang
#EMAIL: senyangjiang@yahoo.com, pipi-max@hotmail.com
#ID: 505111806, 205171726

all:
	@rm -f lab3b
	@ln lab3b.py lab3b
	@chmod +x lab3b

dist:
	@tar -czf lab3b-505111806.tar.gz lab3b.py Makefile README

clean:
	@rm -f lab3b-505111806.tar.gz lab3b
