#NAME: Senyang Jiang
#EMAIL: senyangjiang@yahoo.com
#ID: 505111806

all: lab1b-client.c lab1b-server.c
	@gcc -Wall -Wextra lab1b-client.c -o lab1b-client
	@gcc -Wall -Wextra lab1b-server.c -o lab1b-server
clean:
	@rm -f lab1a lab1a-505111806.tar.gz
dist:
	@tar -czf lab1a-505111806.tar.gz Makefile lab1a.c README
